### ISSUE TITLE
Publish "crawlerlib" and add as a dependency

### ISSUE THREAD

**Issue by rshipp** [InQuest/threat-ingestors#11]
Need the ioc extraction portions of "crawlerlib" published, preferably as a library on PyPi.

We currently use the following features:

* extract_ioc https://github.com/InQuest/threat-ingestors/blob/4c9e7e5604487589453e707c7071d289f49bdddc/sources/__init__.py#L45 https://github.com/InQuest/threat-ingestors/blob/4c9e7e5604487589453e707c7071d289f49bdddc/sources/__init__.py#L66
* extract_yara_rules https://github.com/InQuest/threat-ingestors/blob/4c9e7e5604487589453e707c7071d289f49bdddc/sources/__init__.py#L82

Have discussed possibly publishing an ioc extractor library with these pieces, and moving some of the pre/postprocessing implemented elsewhere in ThreatIngestor into that library as well.

Once this library is published, add it as a dependency to `requirements.txt`.

This is a hard dependency for initial release, as ThreatIngestor requires the IOC extraction to function.

**Comment by SShinol** [comment]
https://github.com/InQuest/threat-ingestors/pull/20
I have it written and added here, tell me if it needs to be moved or anything

**Comment by rshipp** [comment]
Moved to https://github.com/inquest/python-iocextract.
Note: remember to update requirements.txt once this is published.
